framework:
    messenger:
        default_bus: messenger.bus.default
        failure_transport: failed
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    delay: 500
                    multiplier: 2
                    max_delay: 5000
                options:
                    exchange:
                        name: messages
            failed:
                dsn: 'doctrine://default?queue_name=failed'
                options:
                    table_name: failed_messages

        routing:
            App\Application\Transaction\Command\RecordTransactionCommand: async

when@test:
    framework:
        messenger:
            transports:
                # replace with your transport name here (e.g., my_transport: 'in-memory://')
                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
                async: 'sync://'
